### ISSUE TITLE
Sugestões de melhoria do HTML

### ISSUE THREAD

**Issue by lobovit** [deybeatriz/Bikcraft#1]
Sobre o HTML :

1. Adicione um lang atributo ao elemento HTML para indicar o idioma da página. Por exemplo, para português, use: lang="pt-br". Exemplo:

```html
<!DOCTYPE html>
<html lang="pt-br">
````

2. Adicione uma descrição apropriada para as imagens usando o atributo `alt`. Por exemplo, em vez de "Logo Bikcraft", você pode usar "Logotipo da empresa Bikcraft". Exemplo:

```html
<img src="/files/bikcraft.svg" alt="Logotipo da empresa Bikcraft">
````

3. É uma boa prática incluir um `viewport meta` tag na seção <head>, para garantir que a página seja exibida corretamente em dispositivos móveis. Por exemplo, use: `<meta name="viewport" content="width=device-width, initial-scale=1.0">`.  Seu head ficaria assim:

```html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bikcraft</title>
  <link rel="stylesheet" href="/style/style.css">
</head>
````

4. Não é uma boa prática que nome de classes e ids nas tags tenha acentuação. Ex: `<div class=apresentação`. Issso porque pode haver inconsistências entre os navegadores e sistemas operacionais que podem interpretar de maneiras diferentes os caracteres especiais. 

> O recomendável é usar somente caracteres alfanuméricos em nomes de classes e IDs no HTML. Se for necessário usar espaços, é comum usar hífens ou underscores (underline) para separar as palavras, como "classe-exemplo" ou "id_exemplo". Dessa forma, a legibilidade do código é mantida e evita-se problemas de desenvolvimento e compatibilidade.

**Comment by deysebeatriz** [comment]
Opa, agradeço a contribuição!

Normalmente eu utilizo o cabeçalho 
````
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="./style/style.css">
  <title>Bikcraft</title>
</head>
```

Creio que na pressa acabei deixando de colocar ou excluindo sem querer.

Quanto ao restante, vou me atentar :)
