### ISSUE TITLE
Sugestões de melhorias CSS

### ISSUE THREAD

**Issue by lobovit** [deybeatriz/Bikcraft#2]
1. Evite acentuação em nome de classes e IDS (mesma dica do HTML). Portanto, evite isso daqui:

```css
.apresentação
.subtítulo
```

2. Altere o header `a:hover{border: 2px solid #e21;}` para `header a:hover{border-color: #e21;}` para evitar sobrescrever outros atributos de border; Caso não fique tão claro o porque dessa mudança, abaixo explico melhor:

Ao utilizar `header a:hover{border: 2px solid #e21;}`, estamos definindo que quando o usuário passar o mouse sobre qualquer link dentro do elemento `header`, a borda terá uma largura de 2 pixels, será sólida e de cor `#e21`. Porém, essa propriedade `border` irá sobrescrever outras propriedades de borda já definidas para o elemento `a`. Por exemplo, se tivermos definido anteriormente `a{border-radius: 4px;}`, essa borda arredondada será perdida quando o mouse passar sobre o link.

Ao utilizarmos `header a:hover{border-color: #e21;}`, estamos definindo que apenas a cor da borda irá mudar quando o mouse passar sobre o link, deixando intactas outras propriedades de borda previamente definidas. Assim, podemos manter outras características da borda, como a largura e o tipo, sem afetar o layout da página quando o mouse passar sobre o link.

3. Utilize algum arquivo de reset do css:

Considere usar o `normalize.css` além do .css que vc escreveu.

O **[normalize.css](https://necolas.github.io/normalize.css/)** fornece estilos padrão para elementos HTML, mas de uma maneira que preserva as configurações úteis do navegador (por exemplo, as configurações padrão para table ou input). Ele não tenta redefinir todos os estilos padrão, mas sim ajustá-los e harmonizá-los para garantir uma experiência mais consistente em todos os navegadores. Ele é um substituto do arquivo de `reset.css` que serve para deixar o padrão do css zerado para todos os tipos de navegadores e assim seu .css não sofrerá alterações entre os navegadores.

**Comment by deysebeatriz** [comment]
Muito legal, irei me atentar também! Obrigada!
