### ISSUE TITLE
Ajustes

### ISSUE THREAD

**Issue by lobovit** [deybeatriz/Bikcraft#3]
Oi Bea, tdo bom? Muito bom que você ponderou e fez os ajustes. Olha só, mais um ponto a cerca da organização de pastas e arquivos. Talvez seja interessante você seguir um padrão (isso te ajuda a se orientar em projetos que não são de sua autoria como também para que pessoas possam colaborar com seu projeto). Então abaixo está uma estrutura de pastas e arquivos usados no framework **[Bootstrap](https://getbootstrap.com.br/)** (bastante usado a anos):

```bash
projeto/
├── assets/
│   ├── css/
│   │   └── style.css
│   ├── js/
│   │   └──xablau.js
│   ├── img/
│   │   ├── logo.png
│   │   └── background.jpg
│   └── fonts/
│       ├── font1.ttf
│       └── font2.woff
├──.gitattributes
├── LICENSE
├── README.md
├── LICENSE
└── index.html
```

Outro ponto de atenção: https://github.com/deybeatriz/Bikcraft/commits/main observe que vc está usando indevidamente os comentários de commit. Dá uma olhada nesse site: **[https://www.conventionalcommits.org](https://www.conventionalcommits.org)**.

**Comment by deysebeatriz** [comment]
Obrigada! Apliquei a estrutura de pastas e arquivos que vc me indicou.
